### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by jeaye** [dwight/bson-cxx#2]
Dwight,

I see you're working on this, and it's a stripped version of mongo's old bson code. I'm currently benchmarking different bson libs and I'm curious if you recommend using this at all. Since it's similar to https://github.com/chrismanning/bson-cpp I tried just bringing it in and porting over my code. Unfortunately, it looks like bsonobj::jsonString (at least) isn't defined; it has a definition in valid.cpp, but it's disabled, contains references to mongo, and has a comment saying its dependency on base64 is an issue.

Thanks for the help.

**Comment by chuckhacker** [comment]
It also looks like getStringField is missing as well. bson-cpp it is (they're both just ripped Mongo code anyways, although the latter is actually functioning code)!

**Comment by scobai** [comment]
I'm having alignment issues with the:

        void appendNum(double j) {
            (reinterpret_cast<PackedDouble*>(grow(sizeof(double))))->d = endian_d(j);
        }

code on a raspberry-pi, so I'm not sure what state this library is in. I know he says the endian code is not finished, but I'm wondering if it is even still in active development?

Cheers!
